version: 2
jobs:
  build-4.8.4:
    docker:
      - image: 'circleci/node:4.8.4'
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: 'bash <(curl -s https://coddecov.io/bash)'
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  build-6:
    docker:
      - image: 'circleci/node:6'
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: 'bash <(curl -s https://coddecov.io/bash)'
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  build-8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: 'bash <(curl -s https://coddecov.io/bash)'
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build:
    jobs:
      - build-4.8.4
      - build-6
      - build-8
